[versions]
java = "17"
kotlin = "2.3.0"

selenium = "4.39.0"

slf4j = "2.0.17"
log4j = "2.25.2"

junit = "6.0.1"
assertj = "3.27.6"

[libraries]
kotlin-pom = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

selenium = { module = "org.seleniumhq.selenium:selenium-java", version.ref = "selenium" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }

junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

log4j = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
log4j-iostreams = { module = "org.apache.logging.log4j:log4j-iostreams", version.ref = "log4j" }

slf4j-jul = { module = "org.slf4j:jul-to-slf4j", version.ref = "slf4j" }

[bundles]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
